# Generated by Django 3.1.5 on 2021-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mynotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='myfile',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
